and this {
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "ea979488-1fe9-489c-adde-22ddf2ba9cf9",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- ============================================================================\n",
    "-- GLOBAL CLOUD INFRASTRUCTURE SETUP\n",
    "-- ============================================================================\n",
    "\n",
    "-- 1. Create a secure storage link to your AWS S3 bucket\n",
    "CREATE OR REPLACE STORAGE INTEGRATION s3_indian_retail_integration\n",
    "  TYPE = EXTERNAL_STAGE\n",
    "  STORAGE_PROVIDER = 'S3'\n",
    "  ENABLED = TRUE\n",
    "  STORAGE_ALLOWED_LOCATIONS = ('s3://indian-retail-analytics-landing-zone/landing/')\n",
    "  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::767397728224:role/Snowflake_Storage_Integration_Role';\n",
    "\n",
    "-- Verify properties to complete the AWS IAM Role trust handshake\n",
    "DESCRIBE INTEGRATION s3_indian_retail_integration;\n",
    "\n",
    "\n",
    "-- ============================================================================\n",
    "-- DATABASE & MEDALLION LAYER ARCHITECTURE\n",
    "-- ============================================================================\n",
    "\n",
    "CREATE OR REPLACE DATABASE indian_retail_db;\n",
    "\n",
    "CREATE OR REPLACE SCHEMA indian_retail_db.bronze;\n",
    "CREATE OR REPLACE SCHEMA indian_retail_db.silver;\n",
    "CREATE OR REPLACE SCHEMA indian_retail_db.gold;\n",
    "\n",
    "\n",
    "-- ============================================================================\n",
    "-- BRONZE LAYER (RAW DATA INGESTION & DATA LAKE LINK)\n",
    "-- ============================================================================\n",
    "\n",
    "-- 1. Create the External Stage pointing to the S3 Landing Zone\n",
    "CREATE OR REPLACE STAGE indian_retail_db.bronze.s3_landing_stage\n",
    "  STORAGE_INTEGRATION = s3_indian_retail_integration\n",
    "  URL = 's3://indian-retail-analytics-landing-zone/landing/';\n",
    "\n",
    "-- 2. Create Split Semi-Structured Bronze Tables with 30-Day Time Travel Enabled\n",
    "CREATE OR REPLACE TABLE indian_retail_db.bronze.stg_raw_sales (\n",
    "    raw_data VARIANT,\n",
    "    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()\n",
    ") DATA_RETENTION_TIME_IN_DAYS = 30;\n",
    "\n",
    "CREATE OR REPLACE TABLE indian_retail_db.bronze.stg_raw_customers (\n",
    "    raw_data VARIANT,\n",
    "    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()\n",
    ") DATA_RETENTION_TIME_IN_DAYS = 30;\n",
    "\n",
    "CREATE OR REPLACE TABLE indian_retail_db.bronze.stg_raw_products (\n",
    "    raw_data VARIANT,\n",
    "    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()\n",
    ") DATA_RETENTION_TIME_IN_DAYS = 30;\n",
    "\n",
    "\n",
    "-- ============================================================================\n",
    "-- CHANGE DATA CAPTURE (CDC STREAMS FOR DATABRICKS HANDSHAKE)\n",
    "-- ============================================================================\n",
    "\n",
    "CREATE OR REPLACE STREAM indian_retail_db.bronze.sales_cdc_stream ON TABLE indian_retail_db.bronze.stg_raw_sales;\n",
    "CREATE OR REPLACE STREAM indian_retail_db.bronze.customers_cdc_stream ON TABLE indian_retail_db.bronze.stg_raw_customers;\n",
    "CREATE OR REPLACE STREAM indian_retail_db.bronze.products_cdc_stream ON TABLE indian_retail_db.bronze.stg_raw_products;\n",
    "\n",
    "\n",
    "-- ============================================================================\n",
    "-- AUTOMATED INGESTION PIPES (SNOWPIPE RUNTIME ENGINES)\n",
    "-- ============================================================================\n",
    "\n",
    "-- 1. Automated Continuous SALES Ingestion Engine\n",
    "CREATE OR REPLACE PIPE indian_retail_db.bronze.pipe_sales\n",
    "AUTO_INGEST = TRUE\n",
    "AS\n",
    "COPY INTO indian_retail_db.bronze.stg_raw_sales (raw_data) FROM (\n",
    "  SELECT OBJECT_CONSTRUCT(\n",
    "    'Order_ID', $1, 'Customer_ID', $2, 'Product_ID', $3, 'Order_Date', $4, 'Order_Time', $5,\n",
    "    'Delivery_Date', $6, 'Quantity', $7, 'Unit_Price', $8, 'Order_Value', $9, 'Shipping_Cost', $10,\n",
    "    'Coupon_Code', $11, 'Coupon_Discount', $12, 'Total_Amount', $13, 'Payment_Mode', $14,\n",
    "    'Order_Status', $15, 'Rating', $16, 'Review_Text', $17, 'City', $18, 'State', $19,\n",
    "    'Customer_Age', $20, 'Customer_Age_Group', $21\n",
    "  ) FROM @indian_retail_db.bronze.s3_landing_stage\n",
    ")\n",
    "FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '\"' SKIP_HEADER = 1)\n",
    "PATTERN = '.*sales.*\\.csv';\n",
    "\n",
    "-- 2. Automated Continuous PRODUCTS Ingestion Engine\n",
    "CREATE OR REPLACE PIPE indian_retail_db.bronze.pipe_products\n",
    "AUTO_INGEST = TRUE\n",
    "AS\n",
    "COPY INTO indian_retail_db.bronze.stg_raw_products (raw_data) FROM (\n",
    "  SELECT OBJECT_CONSTRUCT(\n",
    "    'Product_ID', $1, 'Product_Name', $2, 'Category', $3, 'Brand', $4, 'Original_Price', $5,\n",
    "    'Discount_Percent', $6, 'Discount_Amount', $7, 'Selling_Price', $8, 'Stock_Quantity', $9,\n",
    "    'Weight_kg', $10, 'Avg_Rating', $11, 'Total_Reviews', $12\n",
    "  ) FROM @indian_retail_db.bronze.s3_landing_stage\n",
    ")\n",
    "FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '\"' SKIP_HEADER = 1)\n",
    "PATTERN = '.*products.*\\.csv';\n",
    "\n",
    "-- 3. Automated Continuous CUSTOMERS Ingestion Engine\n",
    "CREATE OR REPLACE PIPE indian_retail_db.bronze.pipe_customers\n",
    "AUTO_INGEST = TRUE\n",
    "AS\n",
    "COPY INTO indian_retail_db.bronze.stg_raw_customers (raw_data) FROM (\n",
    "  SELECT OBJECT_CONSTRUCT(\n",
    "    'Customer_ID', $1, 'Customer_Name', $2, 'Gender', $3, 'Age', $4, 'Age_Group', $5,\n",
    "    'Date_of_Birth', $6, 'Email', $7, 'Phone', $8, 'City', $9, 'State', $10, 'Pincode', $11,\n",
    "    'Registration_Date', $12, 'Customer_Tier', $13, 'Total_Orders', $14, 'Total_Spent', $15\n",
    "  ) FROM @indian_retail_db.bronze.s3_landing_stage\n",
    ")\n",
    "FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '\"' SKIP_HEADER = 1)\n",
    "PATTERN = '.*customers.*\\.csv';\n",
    "\n",
    "\n",
    "-- ============================================================================\n",
    "-- GOLD LAYER ARCHITECTURE (ANALYTICS-READY STAR SCHEMA)\n",
    "-- ============================================================================\n",
    "\n",
    "CREATE OR REPLACE TABLE indian_retail_db.gold.fact_sales (\n",
    "    order_id STRING,\n",
    "    customer_id STRING,\n",
    "    product_id STRING,\n",
    "    order_date DATE,\n",
    "    quantity INT,\n",
    "    unit_price NUMBER(10,2),\n",
    "    total_amount NUMBER(12,2),\n",
    "    payment_mode STRING,\n",
    "    order_status STRING\n",
    ") DATA_RETENTION_TIME_IN_DAYS = 30; \n",
    "\n",
    "CREATE OR REPLACE TABLE indian_retail_db.gold.dim_customers (\n",
    "    customer_id STRING,\n",
    "    customer_name STRING,\n",
    "    gender STRING,\n",
    "    customer_tier STRING,\n",
    "    city STRING,\n",
    "    state STRING\n",
    ") DATA_RETENTION_TIME_IN_DAYS = 30;\n",
    "\n",
    "CREATE OR REPLACE TABLE indian_retail_db.gold.dim_products (\n",
    "    product_id STRING,\n",
    "    product_name STRING,\n",
    "    category STRING,\n",
    "    brand STRING\n",
    ") DATA_RETENTION_TIME_IN_DAYS = 30;\n",
    "\n",
    "\n",
    "-- ============================================================================\n",
    "-- PIPELINE AUTOMATION & INCREMENTAL SCHEDULER\n",
    "-- ============================================================================\n",
    "\n",
    "CREATE OR REPLACE TASK indian_retail_db.gold.sync_gold_star_schema_task\n",
    "WAREHOUSE = COMPUTE_WH\n",
    "SCHEDULE = '30 MINUTE'\n",
    "AS\n",
    "EXECUTE IMMEDIATE '\n",
    "BEGIN\n",
    "    -- A. Upsert records into FACT_SALES us
